language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

install:
  - composer require --dev cebe/assetfree-yii2 --prefer-dist --no-interaction
  - composer install --prefer-dist --no-interaction
script:
  - make test
